const datas = [
  {
    id: "music-001",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20golden%20hour_64kbps.mp3?alt=media&token=e91240be-67dd-4d03-9cee-ededbd64e183&_gl=1*wob8cf*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTY5NzE1OS4xNC4xLjE2ODU2OTc4OTcuMC4wLjA",
    lyrics: [
      "It was just two lovers",
      "Sittin' in the car, listening to Blonde",
      "Fallin' for each other",
      "Pink and orange skies, feelin' super childish",
      "No Donald Glover",
      "Missed call from my mother",
      'Like, "Where you at tonight?" Got no alibi',
      "I was all alone with the love of my life",
      "She's got glitter for skin",
      "My radiant beam in the night",
      "I don't need no light to see you",
      "Shine",
      "It's your golden hour (oh)",
      "You slow down time",
      "In your golden hour (oh)",
      "We were just two lovers",
      "Feet up on the dash, drivin' nowhere fast",
      "Burnin' through the summer",
      "Radio on blast, make the moment last",
      "She got solar power",
      "Minutes feel like hours",
      "She knew she was the baddest, can you even imagine",
      "Fallin' like I did?",
      "For the love of my life",
      "She's got glow on her face",
      "A glorious look in her eyes",
      "My angel of light",
      "I was all alone with the love of my life",
      "She's got glitter for skin",
      "My radiant beam in the night",
      "I don't need no light to see you",
      "Shine",
      "It's your golden hour (oh)",
      "You slow down time",
      "In your golden hour (oh)",
    ],
    title: "Golden Hour",
    artist: "JVKE",
    image:
      "https://lh3.googleusercontent.com/i1qCCS4BbP6z11E08FkQg6fN-83Uj4fQg4bmBsD2E6SvGQ3RW7nXxpQ3hmcSlI5Ipek10H7R4BjV5mAY=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-002",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Cupid.mp3?alt=media&token=df1326e6-4478-43e9-9aaf-d3264ba39fe6&_gl=1*c9kyw3*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTE4MDQuMC4wLjA.",
    lyrics: [
      "불 꺼진 romantic, all my life",
      "내 주위는 온통 lovely day",
      "내 눈 속에 비친 arrow sign",
      "(Oh, why? Oh, why?)",
      "(Oh, why? Oh, why?)",
      "I'm feeling lonely (lonely)",
      "그만 힐끗대고 말해줘요",
      "Hold me (hold me)",
      "다시 crying in my room",
      "숨기고 싶어 (say what you say, but I want it more)",
      "But still I want it more, more, more",
      "I gave a second chance to Cupid",
      "널 믿은 내가 정말 stupid",
      "보여줄게 숨겨왔던 love, is it real?",
      "Cupid is so dumb",
      "또 꿈길을 걷는 every day",
      "눈 뜨면 다시 또 flew away",
      "Waiting around is a waste (waste)",
      "나 솔직히 지금이 편해",
      "상상만큼 짜릿한 걸까?",
      "Now I'm so lonely (lonely)",
      "매일 꿈속에서 연습했죠",
      "Kiss me (kiss me)",
      "다시 crying in my room",
      "포기할까 봐 (say what you say, but I want it more)",
      "But still I want it more, more, more",
      "I gave a second chance to Cupid",
      "널 믿은 내가 정말 stupid",
      "보여줄게 숨겨왔던 love, is it real?",
      "Cupid is so dumb",
      "I'm so lonely, hold me tightly",
      "짜릿한 걸 원해",
      "Who will really love me truly?",
      "내게 기다림은 없어 I can't wait",
      "더는 믿지 않아 now I'm gonna make it mine",
      "Love is a light, I'll show my love is right",
      "It's not a joke, so give it to me right now",
      "No more chance to you",
      "You know? Hey, d-d-d-dumb boy",
      "꿈속에 매일 밤",
      "Someone who will share this feeling",
      "I'm a fool, a fool for love",
      "A fool for love",
      "I gave a second chance to Cupid",
      "널 믿은 내가 정말 stupid",
      "보여줄게 숨겨왔던 love, is it real?",
      "Cupid is so dumb",
      "I gave a second chance to Cupid (hopeless girl is seeking)",
      "널 믿은 내가 정말 stupid (someone who will share this feeling)",
      "다시 한번 못 들은 척 기회를 줄게 (I'm a fool)",
      "Cupid is so dumb (a fool for love, a fool for love)",
    ],
    title: "Cupid",
    artist: "FIFTY FIFTY",
    image:
      "https://lh3.googleusercontent.com/aNYwueKXyXRauPqG7yd2m7ORbu18oJfE41tjt4mk6YkKrgtTlTl_dtD-9Jncl4MSg8xVG5IjAzcoSwI=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-003",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Kya%20Loge%20Tum.mp3?alt=media&token=5b0ff6dc-6957-44a5-9f37-1a214cbab192&_gl=1*1n2n0k*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIwNTQuMC4wLjA.",
    lyrics: [
      "अर्रे दौलत या शोहरत दुआ लोगे तुम",
      "या कोई महल नया लोगे तुम",
      "अर्रे दौलत या शोहरत दुआ लोगे तुम",
      "या कोई महल नया लोगे तुम",
      "यार मेरे तू बता दे मुझे",
      "हो यार मेरे तू बता दे मुझे",
      "हो मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "ये चाँद या तारे हवा लोगे तुम",
      "या लिखने की मेरी कला लोगे तुम",
      "यार मेरे तू बता दे मुझे",
      "हो यार मेरे तू बता दे मुझे",
      "हो मेरी ज़िंदगी से जाने का",
      "अर्रे कुछ तो बोल मुँह तो खोल",
      "प्यार भी ढूँढ के दे देंगे",
      "अर्रे कुछ तो बोल मुँह तो खोल",
      "प्यार भी ढूँढ के दे देंगे",
      "और क्या कर्दे तुझको",
      "हम नया यार भी",
      "ढूँढ के दे देंगे",
      "और क्या कर्दे तुझको",
      "हम नया यार भी",
      "ढूँढ के",
      "हो मुझको यूँ जल्दी",
      "भूला लोगे तुम",
      "हो जब गैरों से नज़रें",
      "मिला लोगे तुम",
      "यार मेरे तू बता दे मुझे",
      "हो यार मेरे तू बता दे मुझे",
      "हो मेरी ज़िंदगी से जाने का",
      "लावारिस है प्यार तेरा",
      "घर बार कोई नही",
      "तू दुश्मन है अब मेरा",
      "यार वार कोई नही",
      "ओह सनकी है पागल है",
      "पागल बनता है",
      "जैसे मैने छोड़ा",
      "मुझे आँखें यूँ दिखता है",
      "ओह पता नही क्या चाहता है",
      "मन थोड़ी दे देंगे",
      "जान है तो क्या हुआ",
      "जान थोड़ी दे देंगे",
      "हो मेरा भी ज़मीर है",
      "ऐसा थोड़ी होता है",
      "ज़िंदगी में हर चीज़",
      "पैसा थोड़ी होता है",
      "हो इश्क़ भी कोई चीज़ है",
      "खुदा है गवाह है",
      "हो जा जानी तुझे मेरी",
      "ये बद्दुआ है ये बद्दुआ है",
      "के चाहोगे जिसको",
      "गावा लोगे तुम",
      "जो करते हो शायरी",
      "भूला लोगे तुम",
      "यार मेरे तू बता दे मुझे",
      "हो यार मेरे तू बता दे मुझे",
      "हो मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
      "हो मेरी ज़िंदगी से जाने का",
      "क्या लोगे तुम",
    ],
    title: "Kya Loge Tum",
    artist: "B Praak & Jaani",
    image:
      "https://lh3.googleusercontent.com/k0UBB9sGH0AW6TZI4dajyC5XiWiw5VMLERppkFxHLlWNsAiNw4BnEuvXJAbwXRBXGZvhturh62OWmywt=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-004",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20La%20Bebe%20Remix.mp3?alt=media&token=bd5e1223-1e28-44cc-9dd6-4c6a92b89a03&_gl=1*yxccl4*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIxMzIuMC4wLjA.",
    lyrics: [
      "Hoy es noche de estar soltera",
      "Le gusta el perreo y bailar de cerca",
      "Me encanta cuando bellaquea",
      "Quiere que la toque, pe-ro sabes ti",
      "Que esta noche estás pa' mí",
      "Ven, trépate encima 'e mí, manda la ubi', paso por ti",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer",
      "No se le ha olvidado cómo la pasamos",
      "Fuimos a la disco y los dos bailamos pegados",
      "Como perros pegaos, besos y par de tragos",
      "Se quedó a mi lado y dijo: 'creo me he enamorado'",
      "Ella fuma, ella toma",
      "Es diablita, chiquita, pero picosa",
      "Me encanta cuando el pantalón me lo rosa",
      "A ella le encanta, se ve en su cara lo goza",
      "Tiene novio y no se comporta",
      "Me dice: 'tranqui, que la relación 'ta rota'",
      "Nuestros cuerpos chocan y chocan",
      "Se juntan las bocas, los leggings le ahorcan",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer, ayer, ayer",
      "Y te movias muy bien, muy bien",
      "Y se impregnó el olor de Chanel",
      "Tamos 1000 grados farenheit",
      "Está buena y de cara bonita",
      "Le pones música y solita se excita",
      "Pa' la fiesta nunca se limita",
      "Par de amigas, completa la cuadrilla",
      "Pero tú, mamá, sabes, me mamas",
      "Loca, ven pa'cá, pégate hasta atrás",
      "Nos vamos tú y yo en un viaje fugaz",
      "Interestellar, comerte toda",
      "Fumaremos los dos marihuana",
      "En el cuarto, en la azotea y en mi cama",
      "Nena, creo te llaman, contesta mañana",
      "Que no se apague la flama",
      "Llama a los bomberos, que el cuarto se va a incendiar",
      "De tanto calor creo que nos vamos a desmayar",
      "Chica, ven pa'cá, que te voy a bellaquear",
      "Ojitos chinitos como dice Don Omar",
      "La bebé, la bebé",
      "Y hasta abajo la bebé",
      "Hasta abajo la bebé",
      "Hasta abajo la bebé",
      "Hasta abajo la bebé-bé-bé-bé",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer",
      "Quiere que le ponga música",
      "Pa' que baile hasta abajo la bebé (la bebé, la bebé)",
      "Bebimos un par de botellas",
      "Y aun así recuerda que lo hicimo' ayer",
    ],
    title: "La Bebe Remix",
    artist: "Yng Lvcas & Peso Pluma",
    image:
      "https://lh3.googleusercontent.com/i-0UE7zfljTdsNo816mLX2v528i20y34ry_3rNqHZY7O6ZnowZGDXhEgecmL_sp6isLE2aOVskiDLTta=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-005",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Light%20Switch.mp3?alt=media&token=2891599c-da69-4111-93f7-98eba3908f3c&_gl=1*4ieqx2*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIxNzEuMC4wLjA.",
    lyrics: [
      "Yeah",
      "Why you callin' at 11:30",
      "When you only wanna do me dirty?",
      "But I hit right back 'cause you got that, that, yeah",
      "Why you always wanna act like lovers",
      "But you never wanna be each other's?",
      'I say, "Don\'t look back" but I go right back and',
      "All of a sudden, I'm hypnotized",
      "You're the one that I can't deny",
      "Every time that I say I'm gonna walk away",
      "You turn me on like a light switch",
      "When you're movin' your body around and around",
      "Now, I don't wanna fight this (no)",
      "You know how to just make me want",
      "You turn me on like a light switch",
      "When you're movin' your body around and around",
      "You got me in a tight grip (yeah)",
      "You know how to just make me want you, baby",
      "Do you love it when you keep me guessin'? (Me guessin')",
      "When you leave, and then you leave me stressin' (me stressin')",
      "But I can't stay mad when you walk like that, no (uh)",
      "Why you always wanna act like lovers",
      "But you never wanna be each other's?",
      "I say don't look back, but I go right back and",
      "All of a sudden, I'm hypnotized (hypnotized)",
      "You're the one that I can't deny (can't deny)",
      "Every time that I say I'm gonna walk away (yeah)",
      "You turn me on like a light switch",
      "When you're movin' your body around and around",
      "Now, I don't wanna fight this (no)",
      "You know how to just make me want",
      "You turn me on like a light switch (switch)",
      "When you're movin' your body around and around",
      "You got me in a tight grip (grip)",
      "You know how to just make me want you, baby",
      "C'mon, c'mon, c'mon, c'mon",
      "C'mon and show me how you do (do)",
      "You want, you want, you want, you want",
      "You wanna keep me wantin' you (me wantin' you, girl)",
      "C'mon, c'mon, c'mon, c'mon",
      "C'mon and show me how you do (you do)",
      "You want, you want, you want, you want",
      "You wanna keep me wantin' you",
      "You turn me on like a light switch",
      "When you're movin' your body around and around",
      "Now, I don't wanna fight this",
      "You know how to just make me want you",
      "You turn me on like a light switch",
      "When you're movin' your body around and around",
      "You got me in a tight grip",
      "You know how to just make me want you, baby",
      "C'mon, c'mon, c'mon, c'mon",
      "C'mon and show me how you do (how you do)",
      "You want, you want, you want, you want",
      "You wanna keep me wantin' you (baby)",
      "C'mon, c'mon, c'mon, c'mon",
      "C'mon and show me how you do (how you do)",
      "You want, you want, you want, you want",
      "You wanna keep me wantin' you",
    ],
    title: "Light Switch",
    artist: "Charlie Puth",
    image:
      "https://lh3.googleusercontent.com/-bOEvKN08Tg0IPfIAo5pK7Jkw727hAGgySGDYR1U2Nqmsn0s8djPE9maQuJZWqLJS-aWyL2LyxeH0Po=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-006",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Piyar%20Farak%20Wali.mp3?alt=media&token=dc31c873-c496-42a9-9f77-d53720c14049&_gl=1*1xbvibl*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIyMzUuMC4wLjA.",
    lyrics: [
      "Ambyar mak pyar,",
      "Balik kanan bubar jalan",
      "Langkah tegak maju",
      "Ninggalke harapan palsu",
      "Durung nembak wis ditolak",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas",
      "Aku cemburu",
      "Weruh kowe mlaku ro kancaku",
      "Nanging aku sadar",
      "Dudu sopo-sopomu",
      "Rong ndino rong wengi",
      "Durung mbok balesi",
      "Chat ngucapke selamat pagi",
      "Kowe mbales ojo ngganggu lagi ro pacarku",
      "Ambyar mak pyar,",
      "Balik kanan bubar jalan",
      "Langkah tegak maju",
      "Ninggalke harapan palsu",
      "Durung nembak wis ditolak",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas",
      "Ra sah dipeksake",
      "Mikir kowe malah edan dewe",
      "Mergo aku sadar",
      "Kowe wis ono sing nduwe",
      "Senajan loro ati",
      "Kudu dinikmati",
      "Ora perlu ditangisi",
      "Putar gelas lagi",
      "Ambyar mak pyar,",
      "Balik kanan bubar jalan",
      "Langkah tegak maju",
      "Ninggalke harapan palsu",
      "Durung nembak wis ditolak",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas",
      "♫",
      "Ambyar mak pyar,",
      "Balik kanan bubar jalan",
      "Langkah tegak maju",
      "Ninggalke harapan palsu",
      "Durung nembak wis ditolak",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas",
      "Ambyar mak pyar,",
      "Balik kanan bubar jalan",
      "Langkah tegak maju",
      "Ninggalke harapan palsu",
      "Durung nembak wis ditolak",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas",
      "Atiku wis ikhlas",
      "Mbok gawe babak bundhas.",
    ],
    title: "Piyar Farak Wali",
    artist: "Pawan Singh",
    image:
      "https://lh3.googleusercontent.com/vTrz3CzT-r1uSa81IJ4u87c1R6lDPT75Or0B5d0KVKhZ8U8jzPe2djcnz3MAlKn3DcyXq58UcicKjGeL=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-007",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Sen%CC%83orita.mp3?alt=media&token=6e90c253-939b-448e-b356-230617bbb859&_gl=1*1e9f6k*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIzMjguMC4wLjA.",
    lyrics: [
      "I love it when you call me señorita",
      "I wish I could pretend I didn't need ya",
      "But every touch is ooh, la-la-la",
      "It's true, la-la-la",
      "Ooh, I should be running",
      "Ooh, you keep me coming for ya",
      "Land in Miami",
      "The air was hot from summer rain",
      "Sweat dripping off me",
      "Before I even knew her name, la-la-la",
      "It felt like ooh, la-la-la",
      "Yeah, no",
      "Sapphire moonlight",
      "We danced for hours in the sand",
      "Tequila sunrise",
      "Her body fit right in my hands, la-la-la",
      "It felt like ooh, la-la-la, yeah",
      "I love it when you call me señorita",
      "I wish I could pretend I didn't need ya",
      "But every touch is ooh, la-la-la",
      "It's true, la-la-la",
      "Ooh, I should be running",
      "Ooh, you know I love it when you call me señorita",
      "I wish it wasn't so damn hard to leave ya",
      "But every touch is ooh, la-la-la",
      "It's true, la-la-la",
      "Ooh, I should be running",
      "Ooh, you keep me coming for ya",
      "Locked in the hotel",
      "There's just some things that never change",
      "You say we're just friends",
      "But friends don't know the way you taste, la-la-la",
      "'Cause you know it's been a long time coming",
      "Don't you let me fall, oh",
      "Ooh, when your lips undress me",
      "Hooked on your tongue",
      "Ooh, love, your kiss is deadly",
      "Don't stop",
      "I love it when you call me señorita",
      "I wish I could pretend I didn't need ya",
      "But every touch is ooh, la-la-la",
      "It's true, la-la-la",
      "Ooh, I should be running",
      "Ooh, you know I love it when you call me señorita",
      "I wish it wasn't so damn hard to leave ya",
      "But every touch is ooh, la-la-la",
      "It's true, la-la-la (true, la-la)",
      "Ooh, I should be running",
      "Ooh, you keep me coming for ya",
      "All along I've been coming for ya (for ya)",
      "And I hope it meant something to ya (ooh)",
      "Call my name, I'll be coming for ya",
      "Coming for ya, coming for ya, coming for ya",
      "For ya",
      "For ya (oh, she loves it when I call)",
      "For ya",
      "Ooh, I should be running",
      "Ooh, you keep me coming for ya",
    ],
    title: "Senorita",
    artist: "Shawn Mendes & Camila Cabello",
    image:
      "https://lh3.googleusercontent.com/TK-09E9wZOUk84ktqwb-zNBXfnY3Z927d3fpJ3ObwwOyREKzjAQMMYx0pGSjVAAV2zpRJDpDAavlAPSz=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-008",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Sunroof_320kbps.mp3?alt=media&token=06f4c9cb-1b9e-4906-8f1e-8e302db2bcc1&_gl=1*1k0sh0l*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTIzODMuMC4wLjA.",
    lyrics: [
      "La da la da da, la da da da",
      "La da la da di da da, la da da da da",
      "La da la da da, la da da",
      "La da la da di da",
      "I got my head out the sunroof",
      "I'm blasting our favorite tunes",
      "I only got one thing on my mind",
      "You got me stuck on the thought of you",
      "You're making me feel brand new",
      "You're more than the sunshine in my eyes",
      "You got those pretty eyes in your head, you know it",
      "You got me dancing in my bed so let me show it",
      "You are exactly what I want, kinda cool and kinda not",
      "Wanna give myself to you",
      "Yeah, we're driving down the freeway at night",
      "I only got one thing in the back of my mind (you got me stuck on the thought of you)",
      "I'm feeling like this might be my time to shine",
      "With you, with you, with you",
      "I got my head out the sunroof",
      "I'm blasting our favorite tunes",
      "I only got one thing on my mind",
      "You got me stuck on the thought of you",
      "You're making me feel brand new",
      "You're more than the sunshine in my eyes",
      "I got my head out the sunroof",
      "Oh-whoa, oh-whoa, ooh",
      "You got me stuck on the thought of you",
      "Oh-whoa, oh-whoa, ooh",
      "Yeah, we're driving down the freeway at night",
      "I only got one thing in the back of my mind (you got me stuck on the thought of you)",
      "I'm feeling like this might be my time to shine",
      "With you, with you, with you",
      "I got my head out the sunroof",
      "I'm blasting our favorite tunes",
      "I only got one thing on my mind",
      "You got me stuck on the thought of you",
      "You're making me feel brand new",
      "You're more than the sunshine in my eyes",
      "La da la da da, la da da da",
      "La da la da di da da, la da da da da",
      "La da la da da, la da da da",
      "La da la da di da da da",
      "La da la da da, la da da da",
      "La da la da di da da, la da da da da",
      "La da la da da, la da da da",
      "La da la da di da",
    ],
    title: "Sunroof",
    artist: "Nicky Youre & dazy",
    image:
      "https://lh3.googleusercontent.com/ycWkUrLxkMX_xYBpoKA82FbkLdrDBC-sKP_e9-b84Qk-JNFDdiq2L777JcegI5M5z5C2SZNozPnCosUJ=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-009",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20Two%20Moons.mp3?alt=media&token=6d0736ab-eaa3-4178-b536-c3da9b3915ec&_gl=1*1budzn9*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTI0OTguMC4wLjA.",
    lyrics: [
      "Two moons, I can feel myself start catching on fire",
      "But you knew, yeah, you kept it to yourself, to yourself",
      "Two moons, I get lost on my way searching for liars",
      "This ain't good for my health, no, this ain't good for my health",
      "Sorry, please excuse me for my mess",
      "My heart's been pouring through my chest",
      "I fell through corridors of broken floors",
      "I'm sorry that I left",
      "Fell asleep in my new bed",
      "I can't feel happy in my head",
      "I see two moons and nothing more",
      "I close my door, I'm left with less",
      "I don't feel serene (no)",
      "No, I don't feel too clean (oh)",
      "And I don't want to be the one to make you cry",
      "I'll play inside, I'll start a fire",
      "I'll tell your friends that I lost my mind",
      "It'll take a while but I'll start to smile",
      "Broken windows and broken tiles",
      "Frozen willows, we'll go for miles",
      "Hope will let go, yeah, that's its style",
      "And you don't know where my soul's headed",
      "I'm forgetting you, so I'll say",
      "Sorry, please excuse me for my mess",
      "My heart's been pouring through my chest",
      "I fell through corridors of broken floors",
      "I'm sorry that I left",
      "Fell asleep in my new bed",
      "I can't feel happy in my head",
      "I see two moons and nothing more",
      "I close my door, I'm left with less",
      "Left, right, my eyesight is diminishing",
      "My life sucks at night, I try to finish it",
      "Early, pearly, whites get blurry",
      "Surely I'll go bite the dirty dust",
      "Cuts deeper as my head goes nuts",
      "I'll be a believer if I ever see trust",
      "I must be disgusting rust",
      "God, I hate myself, I just wanna unplug",
      "Yeah, fuck no",
      "I go where I want to",
      "But I'm stuck in my bedroom",
      "I'm telling lies to keep myself from hurting those around you",
      "Yeah, after all these years I found you",
      "I found you again",
      "Sorry, please excuse me for my mess",
      "My heart's been pouring through my chest",
      "I fell through corridors of broken floors",
      "I'm sorry that I left",
      "Fell asleep in my new bed",
      "I can't feel happy in my head",
      "I see two moons and nothing more",
      "I close my door, I'm left with less",
    ],
    title: "Two Moon",
    artist: "Boy with Uke",
    image:
      "https://lh3.googleusercontent.com/EfkMT3K05GQM0zYC0LtZW0j9SVj2LKz01piElNYkw6vOwxSt63H580OaTCBcVdaSX7WawqVXhrCi7PZc=w544-h544-l90-rj",
    like: false,
  },
  {
    id: "music-010",
    music:
      "https://firebasestorage.googleapis.com/v0/b/matrik-music.appspot.com/o/music%2Ftomp3.cc%20-%20%E3%82%A2%E3%82%A4%E3%83%88%E3%82%99%E3%83%AB.mp3?alt=media&token=138af303-e303-497b-9de8-18482ec2e9fd&_gl=1*l9205n*_ga*MTQwNzc2MjE2OS4xNjg1NDEyNTc5*_ga_CW55HF8NVT*MTY4NTg5MTMwMy4xOC4xLjE2ODU4OTI1NDUuMC4wLjA.",
    lyrics: [
      "Shizumu you ni tokete yuku you ni",
      "Futaridake no sora ga hirogaru yoru ni",
      "'Sayonara' dake datta",
      "Sono hitokoto de subete ga wakatta",
      "Higa shizumi dashita sora to kimi no sugata",
      "Fensu-goshi ni kasanatte ita",
      "Hajimete atta hi kara",
      "Boku no kokoro no subete wo ubatta",
      "Doko ka hakanai kuuki wo matou kimi wa",
      "Sabishii me wo shiteta nda",
      "Itsu datte chikkutakku to",
      "Naru sekai de nando datte sa",
      "Fureru kokoronai kotoba urusai koe ni",
      "Namida ga kobore-sou demo",
      "Arikitarina yorokobi kitto futari nara mitsukerareru",
      "Sawagashii hibi ni waraenai kimi ni",
      "Omoitsuku kagiri mabushii asu wo",
      "Akenai yoru ni ochite yuku mae ni",
      "Boku no te wo tsukande hora",
      "Wasurete shimaitakute tojikometa hibi mo",
      "Dakishimeta nukumori de tokasu kara",
      "Kowakunai yo itsuka hi ga noboru made",
      "Futari de iyou",
      "Kimi ni shika mienai",
      "Nanika wo mitsumeru kimi ga kiraida",
      "Mitorete iru ka no you na koi suru you na",
      "Sonna kao ga kirai da",
      "Shinjite itai kedo shinjirenai koto",
      "Son'na no dou shitatte kitto",
      "Korekara datte ikutsu mo atte",
      "Sono tanbi okotte naite iku no",
      "Soredemo kitto itsuka wa kitto bokura wa kitto",
      "Wakari aeru sa shinjiteru yo",
      "Mou iya da tte tsukareta n datte",
      "Gamushara ni sashinobeta boku no te wo furiharau kimi",
      "Mou iya da tte tsukaretayo nante",
      "Hontou wa boku mo iitai nda",
      "Hora mata chikkutakku to",
      "Naru sekai de nando datte sa",
      "Kimi no tame ni yooi shita kotoba dore mo todokanai",
      "'Owari ni shitai' da nante sa",
      "Tsurarete kotoba ni shita toki",
      "Kimi wa hajimete waratta",
      "Sawagashii hibi ni waraenaku natte ita",
      "Boku no meniutsuru kimi wa kirei da",
      "Akenai yoru ni koboreta namida mo",
      "Kimi no egao ni tokete iku",
      "Kawaranai hibi ni naiteita boku wo",
      "Kimi wa yasashiku owari e to sashou",
      "Shizumu you ni tokete yuku you ni",
      "Shimitsuita kiri ga hareru",
      "Wasurete shimaitakute tojikometa hibi ni",
      "Sashinobete kureta kimi no te wo toru",
      "Suzushii kaze ga sora wo oyogu you ni ima fukinukete iku",
      "Tsunaida te wo hanasanaide yo",
      "Futari ima, yoru ni kakedashite iku",
    ],
    title: "yoasobi",
    artist: "YOASOBI",
    image:
      "https://lh3.googleusercontent.com/AjWNrfzz6BqjRL5diZ-bPxFqGOsNk20xS6jcqoQWpNGWdch404mDWKVBkl4s9n74aLjXJWgldqm3Dc8=w544-h544-l90-rj",
    like: false,
  },
];

module.exports = datas;
